SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_PROCESAR_OBLIGACIONES_MES (
    P_ID_USUARIO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ESTADO_PAGO VARCHAR(20)
)
RETURNS (
    ID_OBLIGACION INTEGER,
    NOMBRE_OBLIGACION VARCHAR(100),
    NOMBRE_CATEGORIA VARCHAR(60),
    MONTO_FIJO_MENSUAL DECIMAL(18,2),
    DIA_VENCIMIENTO INTEGER,
    DIAS_PARA_VENCER INTEGER,
    ESTADO_PAGO VARCHAR(20),
    FECHA_ULTIMO_PAGO DATE,
    ALERTA VARCHAR(200)
)
AS
DECLARE VARIABLE PAGOS INTEGER;
BEGIN
    FOR SELECT
            O.ID_OBLIGACION,
            O.NOMBRE_OBLIGACION,
            C.NOMBRE_CATEGORIA,
            O.MONTO_FIJO_MENSUAL,
            O.DIA_VENCIMIENTO,
            FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION)
        FROM OBLIGACION_FIJA O
        INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = O.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE O.ID_USUARIO = :P_ID_USUARIO
          AND O.VIGENTE = TRUE
        ORDER BY O.DIA_VENCIMIENTO
        INTO
            :ID_OBLIGACION,
            :NOMBRE_OBLIGACION,
            :NOMBRE_CATEGORIA,
            :MONTO_FIJO_MENSUAL,
            :DIA_VENCIMIENTO,
            :DIAS_PARA_VENCER
    DO
    BEGIN
        SELECT COUNT(*), MAX(FECHA)
        FROM TRANSACCION
        WHERE ID_OBLIGACION = :ID_OBLIGACION
          AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
          AND ANIO = :P_ANIO
          AND MES = :P_MES
        INTO :PAGOS, :FECHA_ULTIMO_PAGO;

        ALERTA = NULL;

        IF (PAGOS > 0) THEN
            ESTADO_PAGO = 'pagado';
        ELSE
        BEGIN
            IF (DIAS_PARA_VENCER < 0) THEN
            BEGIN
                ESTADO_PAGO = 'vencido';
                ALERTA = 'La obligacion vencio y no tiene pago registrado';
            END
            ELSE
            BEGIN
                ESTADO_PAGO = 'pendiente';

                IF (DIAS_PARA_VENCER <= 3) THEN
                    ALERTA = 'La obligacion vence en 3 dias o menos';
            END
        END

        IF (P_ESTADO_PAGO IS NULL OR ESTADO_PAGO = :P_ESTADO_PAGO) THEN
            SUSPEND;
    END
END^

SET TERM ; ^