CREATE OR ALTER EXCEPTION EX_SUBCATEGORIA_DIFERENTE
'Si la transaccion paga una obligacion debe usar la misma subcategoria de esa obligacion';

SET TERM ^ ;



CREATE OR ALTER PROCEDURE SP_INSERTAR_TRANSACCION (
    P_ID_USUARIO INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_OBLIGACION INTEGER,
    P_TIPO_TRANSACCION VARCHAR(20),
    P_DESCRIPCION VARCHAR(200),
    P_MONTO DECIMAL(18,2),
    P_FECHA DATE,
    P_METODO_PAGO VARCHAR(30),
    P_NUM_FACTURA VARCHAR(40),
    P_OBSERVACIONES VARCHAR(200),
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
DECLARE VARIABLE SUBCAT_OBLIGACION INTEGER;
BEGIN
    IF (P_ID_OBLIGACION IS NOT NULL) THEN
    BEGIN
        SELECT ID_SUBCATEGORIA
        FROM OBLIGACION_FIJA
        WHERE ID_OBLIGACION = :P_ID_OBLIGACION
        INTO :SUBCAT_OBLIGACION;

        IF (SUBCAT_OBLIGACION <> P_ID_SUBCATEGORIA) THEN
            EXCEPTION EX_SUBCATEGORIA_DIFERENTE;
    END

    INSERT INTO TRANSACCION (
        ID_USUARIO,
        ID_PRESUPUESTO,
        ANIO,
        MES,
        ID_SUBCATEGORIA,
        ID_OBLIGACION,
        TIPO_TRANSACCION,
        DESCRIPCION,
        MONTO,
        FECHA,
        METODO_PAGO,
        NUM_FACTURA,
        OBSERVACIONES,
        FECHA_REGISTRO,
        CREADO_POR
    )
    VALUES (
        :P_ID_USUARIO,
        :P_ID_PRESUPUESTO,
        :P_ANIO,
        :P_MES,
        :P_ID_SUBCATEGORIA,
        :P_ID_OBLIGACION,
        :P_TIPO_TRANSACCION,
        :P_DESCRIPCION,
        :P_MONTO,
        :P_FECHA,
        :P_METODO_PAGO,
        :P_NUM_FACTURA,
        :P_OBSERVACIONES,
        CURRENT_TIMESTAMP,
        :P_CREADO_POR
    )
    RETURNING ID_TRANSACCION INTO :NUEVO_ID;
END^



CREATE OR ALTER PROCEDURE SP_CONSULTAR_TRANSACCION (
    P_ID_TRANSACCION INTEGER
)
RETURNS (
    ID_TRANSACCION INTEGER,
    ID_USUARIO INTEGER,
    ID_PRESUPUESTO INTEGER,
    ANIO INTEGER,
    MES INTEGER,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    NOMBRE_CATEGORIA VARCHAR(60),
    ID_OBLIGACION INTEGER,
    NOMBRE_OBLIGACION VARCHAR(100),
    TIPO_TRANSACCION VARCHAR(20),
    DESCRIPCION VARCHAR(200),
    MONTO DECIMAL(18,2),
    FECHA DATE,
    METODO_PAGO VARCHAR(30),
    NUM_FACTURA VARCHAR(40),
    OBSERVACIONES VARCHAR(200),
    FECHA_REGISTRO TIMESTAMP,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            T.ID_TRANSACCION,
            T.ID_USUARIO,
            T.ID_PRESUPUESTO,
            T.ANIO,
            T.MES,
            T.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            C.NOMBRE_CATEGORIA,
            T.ID_OBLIGACION,
            O.NOMBRE_OBLIGACION,
            T.TIPO_TRANSACCION,
            T.DESCRIPCION,
            T.MONTO,
            T.FECHA,
            T.METODO_PAGO,
            T.NUM_FACTURA,
            T.OBSERVACIONES,
            T.FECHA_REGISTRO,
            T.CREADO_POR,
            T.MODIFICADO_POR,
            T.CREADO_EN,
            T.MODIFICADO_EN
        FROM TRANSACCION T
        INNER JOIN SUBCATEGORIA S 
        ON S.ID_SUBCATEGORIA = T.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C 
        ON C.ID_CATEGORIA = S.ID_CATEGORIA
        LEFT JOIN OBLIGACION_FIJA O 
        ON O.ID_OBLIGACION = T.ID_OBLIGACION
        WHERE T.ID_TRANSACCION = :P_ID_TRANSACCION
        INTO
            :ID_TRANSACCION,
            :ID_USUARIO,
            :ID_PRESUPUESTO,
            :ANIO,
            :MES,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :NOMBRE_CATEGORIA,
            :ID_OBLIGACION,
            :NOMBRE_OBLIGACION,
            :TIPO_TRANSACCION,
            :DESCRIPCION,
            :MONTO,
            :FECHA,
            :METODO_PAGO,
            :NUM_FACTURA,
            :OBSERVACIONES,
            :FECHA_REGISTRO,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_TRANSACCIONES_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_TIPO_TRANSACCION VARCHAR(20)
)
RETURNS (
    ID_TRANSACCION INTEGER,
    ANIO INTEGER,
    MES INTEGER,
    FECHA DATE,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    NOMBRE_CATEGORIA VARCHAR(60),
    TIPO_TRANSACCION VARCHAR(20),
    DESCRIPCION VARCHAR(200),
    MONTO DECIMAL(18,2),
    METODO_PAGO VARCHAR(30),
    NOMBRE_OBLIGACION VARCHAR(100)
)
AS
BEGIN
    FOR SELECT
            T.ID_TRANSACCION,
            T.ANIO,
            T.MES,
            T.FECHA,
            T.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            C.NOMBRE_CATEGORIA,
            T.TIPO_TRANSACCION,
            T.DESCRIPCION,
            T.MONTO,
            T.METODO_PAGO,
            O.NOMBRE_OBLIGACION
        FROM TRANSACCION T
        INNER JOIN SUBCATEGORIA S 
        ON S.ID_SUBCATEGORIA = T.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C 
        ON C.ID_CATEGORIA = S.ID_CATEGORIA
        LEFT JOIN OBLIGACION_FIJA O 
        ON O.ID_OBLIGACION = T.ID_OBLIGACION
        WHERE T.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
          AND (:P_ANIO IS NULL OR T.ANIO = :P_ANIO)
          AND (:P_MES IS NULL OR T.MES = :P_MES)
          AND (:P_ID_SUBCATEGORIA IS NULL OR T.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA)
          AND (:P_TIPO_TRANSACCION IS NULL OR T.TIPO_TRANSACCION = :P_TIPO_TRANSACCION)
        ORDER BY T.ANIO, T.MES, T.FECHA
        INTO
            :ID_TRANSACCION,
            :ANIO,
            :MES,
            :FECHA,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :NOMBRE_CATEGORIA,
            :TIPO_TRANSACCION,
            :DESCRIPCION,
            :MONTO,
            :METODO_PAGO,
            :NOMBRE_OBLIGACION
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_TRANSACCION (
    P_ID_TRANSACCION INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_TIPO_TRANSACCION VARCHAR(20),
    P_DESCRIPCION VARCHAR(200),
    P_MONTO DECIMAL(18,2),
    P_FECHA DATE,
    P_METODO_PAGO VARCHAR(30),
    P_NUM_FACTURA VARCHAR(40),
    P_OBSERVACIONES VARCHAR(200),
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE TRANSACCION
    SET ANIO = :P_ANIO,
        MES = :P_MES,
        ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA,
        TIPO_TRANSACCION = :P_TIPO_TRANSACCION,
        DESCRIPCION = :P_DESCRIPCION,
        MONTO = :P_MONTO,
        FECHA = :P_FECHA,
        METODO_PAGO = :P_METODO_PAGO,
        NUM_FACTURA = :P_NUM_FACTURA,
        OBSERVACIONES = :P_OBSERVACIONES,
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_TRANSACCION = :P_ID_TRANSACCION;
END^



CREATE OR ALTER PROCEDURE SP_ELIMINAR_TRANSACCION (
    P_ID_TRANSACCION INTEGER
)
AS
BEGIN
    DELETE FROM TRANSACCION
    WHERE ID_TRANSACCION = :P_ID_TRANSACCION;
END^

SET TERM ; ^





