CREATE OR ALTER EXCEPTION EX_PRESUPUESTO_CON_TRANSACCIONES
'No se puede eliminar el presupuesto porque tiene transacciones registradas';

SET TERM ^ ;



CREATE OR ALTER PROCEDURE SP_INSERTAR_PRESUPUESTO (
    P_ID_USUARIO INTEGER,
    P_NOMBRE_PRESUPUESTO VARCHAR(100),
    P_ANIO_INICIO INTEGER,
    P_MES_INICIO INTEGER,
    P_ANIO_FIN INTEGER,
    P_MES_FIN INTEGER,
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    INSERT INTO PRESUPUESTO (
        ID_USUARIO,
        NOMBRE_PRESUPUESTO,
        ANIO_INICIO,
        MES_INICIO,
        ANIO_FIN,
        MES_FIN,
        TOTAL_INGRESOS_PLANIFICADOS,
        TOTAL_GASTOS_PLANIFICADOS,
        TOTAL_AHORRO_PLANIFICADO,
        FECHA_CREACION,
        ESTADO_PRESUPUESTO,
        CREADO_POR
    )
    VALUES (
        :P_ID_USUARIO,
        :P_NOMBRE_PRESUPUESTO,
        :P_ANIO_INICIO,
        :P_MES_INICIO,
        :P_ANIO_FIN,
        :P_MES_FIN,
        0,
        0,
        0,
        CURRENT_TIMESTAMP,
        'activo',
        :P_CREADO_POR
    )
    RETURNING ID_PRESUPUESTO INTO :NUEVO_ID;
END^



CREATE OR ALTER PROCEDURE SP_CONSULTAR_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER
)
RETURNS (
    ID_PRESUPUESTO INTEGER,
    ID_USUARIO INTEGER,
    NOMBRE_PRESUPUESTO VARCHAR(100),
    ANIO_INICIO INTEGER,
    MES_INICIO INTEGER,
    ANIO_FIN INTEGER,
    MES_FIN INTEGER,
    TOTAL_INGRESOS_PLANIFICADOS DECIMAL(18,2),
    TOTAL_GASTOS_PLANIFICADOS DECIMAL(18,2),
    TOTAL_AHORRO_PLANIFICADO DECIMAL(18,2),
    FECHA_CREACION TIMESTAMP,
    ESTADO_PRESUPUESTO VARCHAR(20),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            P.ID_PRESUPUESTO,
            P.ID_USUARIO,
            P.NOMBRE_PRESUPUESTO,
            P.ANIO_INICIO,
            P.MES_INICIO,
            P.ANIO_FIN,
            P.MES_FIN,
            P.TOTAL_INGRESOS_PLANIFICADOS,
            P.TOTAL_GASTOS_PLANIFICADOS,
            P.TOTAL_AHORRO_PLANIFICADO,
            P.FECHA_CREACION,
            P.ESTADO_PRESUPUESTO,
            P.CREADO_POR,
            P.MODIFICADO_POR,
            P.CREADO_EN,
            P.MODIFICADO_EN
        FROM PRESUPUESTO P
        WHERE P.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
        INTO
            :ID_PRESUPUESTO,
            :ID_USUARIO,
            :NOMBRE_PRESUPUESTO,
            :ANIO_INICIO,
            :MES_INICIO,
            :ANIO_FIN,
            :MES_FIN,
            :TOTAL_INGRESOS_PLANIFICADOS,
            :TOTAL_GASTOS_PLANIFICADOS,
            :TOTAL_AHORRO_PLANIFICADO,
            :FECHA_CREACION,
            :ESTADO_PRESUPUESTO,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_PRESUPUESTOS_USUARIO (
    P_ID_USUARIO INTEGER,
    P_ESTADO_PRESUPUESTO VARCHAR(20)
)
RETURNS (
    ID_PRESUPUESTO INTEGER,
    NOMBRE_PRESUPUESTO VARCHAR(100),
    ANIO_INICIO INTEGER,
    MES_INICIO INTEGER,
    ANIO_FIN INTEGER,
    MES_FIN INTEGER,
    TOTAL_INGRESOS_PLANIFICADOS DECIMAL(18,2),
    TOTAL_GASTOS_PLANIFICADOS DECIMAL(18,2),
    TOTAL_AHORRO_PLANIFICADO DECIMAL(18,2),
    ESTADO_PRESUPUESTO VARCHAR(20)
)
AS
BEGIN
    FOR SELECT
            P.ID_PRESUPUESTO,
            P.NOMBRE_PRESUPUESTO,
            P.ANIO_INICIO,
            P.MES_INICIO,
            P.ANIO_FIN,
            P.MES_FIN,
            P.TOTAL_INGRESOS_PLANIFICADOS,
            P.TOTAL_GASTOS_PLANIFICADOS,
            P.TOTAL_AHORRO_PLANIFICADO,
            P.ESTADO_PRESUPUESTO
        FROM PRESUPUESTO P
        WHERE P.ID_USUARIO = :P_ID_USUARIO
          AND (:P_ESTADO_PRESUPUESTO IS NULL OR P.ESTADO_PRESUPUESTO = :P_ESTADO_PRESUPUESTO)
        ORDER BY P.ANIO_INICIO DESC, P.MES_INICIO DESC
        INTO
            :ID_PRESUPUESTO,
            :NOMBRE_PRESUPUESTO,
            :ANIO_INICIO,
            :MES_INICIO,
            :ANIO_FIN,
            :MES_FIN,
            :TOTAL_INGRESOS_PLANIFICADOS,
            :TOTAL_GASTOS_PLANIFICADOS,
            :TOTAL_AHORRO_PLANIFICADO,
            :ESTADO_PRESUPUESTO
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER,
    P_NOMBRE_PRESUPUESTO VARCHAR(100),
    P_ANIO_INICIO INTEGER,
    P_MES_INICIO INTEGER,
    P_ANIO_FIN INTEGER,
    P_MES_FIN INTEGER,
    P_ESTADO_PRESUPUESTO VARCHAR(20),
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE PRESUPUESTO
    SET NOMBRE_PRESUPUESTO = :P_NOMBRE_PRESUPUESTO,
        ANIO_INICIO = :P_ANIO_INICIO,
        MES_INICIO = :P_MES_INICIO,
        ANIO_FIN = :P_ANIO_FIN,
        MES_FIN = :P_MES_FIN,
        ESTADO_PRESUPUESTO = :P_ESTADO_PRESUPUESTO,
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO;
END^



CREATE OR ALTER PROCEDURE SP_ELIMINAR_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER
)
AS
DECLARE VARIABLE CANTIDAD INTEGER;
BEGIN
    SELECT COUNT(*)
    FROM TRANSACCION
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_PRESUPUESTO_CON_TRANSACCIONES;

    DELETE FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO;

    DELETE FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO;
END^

SET TERM ; ^



