SET TERM ^ ;



CREATE OR ALTER PROCEDURE SP_RECALCULAR_TOTALES_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER
)
AS
DECLARE VARIABLE TOTAL_INGRESOS DECIMAL(18,2);
DECLARE VARIABLE TOTAL_GASTOS DECIMAL(18,2);
DECLARE VARIABLE TOTAL_AHORRO DECIMAL(18,2);
BEGIN
    SELECT COALESCE(SUM(D.MONTO_MENSUAL_ASIGNADO), 0)
    FROM PRESUPUESTO_DETALLE D
    INNER JOIN SUBCATEGORIA S 
    ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
    INNER JOIN CATEGORIA C 
    ON C.ID_CATEGORIA = S.ID_CATEGORIA
    WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND C.TIPO_CATEGORIA = 'ingreso'
    INTO :TOTAL_INGRESOS;

    SELECT COALESCE(SUM(D.MONTO_MENSUAL_ASIGNADO), 0)
    FROM PRESUPUESTO_DETALLE D
    INNER JOIN SUBCATEGORIA S 
    ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
    INNER JOIN CATEGORIA C 
    ON C.ID_CATEGORIA = S.ID_CATEGORIA
    WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND C.TIPO_CATEGORIA = 'gasto'
    INTO :TOTAL_GASTOS;

    SELECT COALESCE(SUM(D.MONTO_MENSUAL_ASIGNADO), 0)
    FROM PRESUPUESTO_DETALLE D
    INNER JOIN SUBCATEGORIA S 
    ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
    INNER JOIN CATEGORIA C 
    ON C.ID_CATEGORIA = S.ID_CATEGORIA
    WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND C.TIPO_CATEGORIA = 'ahorro'
    INTO :TOTAL_AHORRO;

    UPDATE PRESUPUESTO
    SET TOTAL_INGRESOS_PLANIFICADOS = :TOTAL_INGRESOS,
        TOTAL_GASTOS_PLANIFICADOS = :TOTAL_GASTOS,
        TOTAL_AHORRO_PLANIFICADO = :TOTAL_AHORRO
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO;
END^



CREATE OR ALTER PROCEDURE SP_INSERTAR_PRESUPUESTO_DETALLE (
    P_ID_PRESUPUESTO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_MONTO_MENSUAL_ASIGNADO DECIMAL(18,2),
    P_OBSERVACIONES VARCHAR(200),
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    INSERT INTO PRESUPUESTO_DETALLE (
        ID_PRESUPUESTO,
        ID_SUBCATEGORIA,
        MONTO_MENSUAL_ASIGNADO,
        OBSERVACIONES,
        CREADO_POR
    )
    VALUES (
        :P_ID_PRESUPUESTO,
        :P_ID_SUBCATEGORIA,
        :P_MONTO_MENSUAL_ASIGNADO,
        :P_OBSERVACIONES,
        :P_CREADO_POR
    )
    RETURNING ID_DETALLE INTO :NUEVO_ID;

    EXECUTE PROCEDURE SP_RECALCULAR_TOTALES_PRESUPUESTO(:P_ID_PRESUPUESTO);
END^



CREATE OR ALTER PROCEDURE SP_CONSULTAR_PRESUPUESTO_DETALLE (
    P_ID_DETALLE INTEGER
)
RETURNS (
    ID_DETALLE INTEGER,
    ID_PRESUPUESTO INTEGER,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    ID_CATEGORIA INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    TIPO_CATEGORIA VARCHAR(20),
    MONTO_MENSUAL_ASIGNADO DECIMAL(18,2),
    OBSERVACIONES VARCHAR(200),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            D.ID_DETALLE,
            D.ID_PRESUPUESTO,
            D.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            C.ID_CATEGORIA,
            C.NOMBRE_CATEGORIA,
            C.TIPO_CATEGORIA,
            D.MONTO_MENSUAL_ASIGNADO,
            D.OBSERVACIONES,
            D.CREADO_POR,
            D.MODIFICADO_POR,
            D.CREADO_EN,
            D.MODIFICADO_EN
        FROM PRESUPUESTO_DETALLE D
        INNER JOIN SUBCATEGORIA S 
        ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C 
        ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE D.ID_DETALLE = :P_ID_DETALLE
        INTO
            :ID_DETALLE,
            :ID_PRESUPUESTO,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :ID_CATEGORIA,
            :NOMBRE_CATEGORIA,
            :TIPO_CATEGORIA,
            :MONTO_MENSUAL_ASIGNADO,
            :OBSERVACIONES,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_DETALLES_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER
)
RETURNS (
    ID_DETALLE INTEGER,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    ID_CATEGORIA INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    TIPO_CATEGORIA VARCHAR(20),
    MONTO_MENSUAL_ASIGNADO DECIMAL(18,2),
    OBSERVACIONES VARCHAR(200)
)
AS
BEGIN
    FOR SELECT
            D.ID_DETALLE,
            D.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            C.ID_CATEGORIA,
            C.NOMBRE_CATEGORIA,
            C.TIPO_CATEGORIA,
            D.MONTO_MENSUAL_ASIGNADO,
            D.OBSERVACIONES
        FROM PRESUPUESTO_DETALLE D
        INNER JOIN SUBCATEGORIA S 
        ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C 
        ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
        ORDER BY C.TIPO_CATEGORIA, C.NOMBRE_CATEGORIA, S.NOMBRE_SUBCATEGORIA
        INTO
            :ID_DETALLE,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :ID_CATEGORIA,
            :NOMBRE_CATEGORIA,
            :TIPO_CATEGORIA,
            :MONTO_MENSUAL_ASIGNADO,
            :OBSERVACIONES
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PRESUPUESTO_DETALLE (
    P_ID_DETALLE INTEGER,
    P_MONTO_MENSUAL_ASIGNADO DECIMAL(18,2),
    P_OBSERVACIONES VARCHAR(200),
    P_MODIFICADO_POR INTEGER
)
AS
DECLARE VARIABLE ID_PRES INTEGER;
BEGIN
    SELECT ID_PRESUPUESTO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_DETALLE = :P_ID_DETALLE
    INTO :ID_PRES;

    UPDATE PRESUPUESTO_DETALLE
    SET MONTO_MENSUAL_ASIGNADO = :P_MONTO_MENSUAL_ASIGNADO,
        OBSERVACIONES = :P_OBSERVACIONES,
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_DETALLE = :P_ID_DETALLE;

    EXECUTE PROCEDURE SP_RECALCULAR_TOTALES_PRESUPUESTO(:ID_PRES);
END^



CREATE OR ALTER PROCEDURE SP_ELIMINAR_PRESUPUESTO_DETALLE (
    P_ID_DETALLE INTEGER
)
AS
DECLARE VARIABLE ID_PRES INTEGER;
BEGIN
    SELECT ID_PRESUPUESTO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_DETALLE = :P_ID_DETALLE
    INTO :ID_PRES;

    DELETE FROM PRESUPUESTO_DETALLE
    WHERE ID_DETALLE = :P_ID_DETALLE;

    EXECUTE PROCEDURE SP_RECALCULAR_TOTALES_PRESUPUESTO(:ID_PRES);
END^

SET TERM ; ^