SET TERM ^ ;


CREATE OR ALTER PROCEDURE SP_INSERTAR_OBLIGACION (
    P_ID_USUARIO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_NOMBRE_OBLIGACION VARCHAR(100),
    P_DESCRIPCION_OBLIGACION VARCHAR(200),
    P_MONTO_FIJO_MENSUAL DECIMAL(18,2),
    P_DIA_VENCIMIENTO INTEGER,
    P_FECHA_INICIO DATE,
    P_FECHA_FINALIZACION DATE,
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    INSERT INTO OBLIGACION_FIJA (
        ID_USUARIO,
        ID_SUBCATEGORIA,
        NOMBRE_OBLIGACION,
        DESCRIPCION_OBLIGACION,
        MONTO_FIJO_MENSUAL,
        DIA_VENCIMIENTO,
        VIGENTE,
        FECHA_INICIO,
        FECHA_FINALIZACION,
        CREADO_POR
    )
    VALUES (
        :P_ID_USUARIO,
        :P_ID_SUBCATEGORIA,
        :P_NOMBRE_OBLIGACION,
        :P_DESCRIPCION_OBLIGACION,
        :P_MONTO_FIJO_MENSUAL,
        :P_DIA_VENCIMIENTO,
        TRUE,
        :P_FECHA_INICIO,
        :P_FECHA_FINALIZACION,
        :P_CREADO_POR
    )
    RETURNING ID_OBLIGACION INTO :NUEVO_ID;
END^



CREATE OR ALTER PROCEDURE SP_CONSULTAR_OBLIGACION (
    P_ID_OBLIGACION INTEGER
)
RETURNS (
    ID_OBLIGACION INTEGER,
    ID_USUARIO INTEGER,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    NOMBRE_CATEGORIA VARCHAR(60),
    NOMBRE_OBLIGACION VARCHAR(100),
    DESCRIPCION_OBLIGACION VARCHAR(200),
    MONTO_FIJO_MENSUAL DECIMAL(18,2),
    DIA_VENCIMIENTO INTEGER,
    VIGENTE BOOLEAN,
    FECHA_INICIO DATE,
    FECHA_FINALIZACION DATE,
    DIAS_PARA_VENCER INTEGER,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            O.ID_OBLIGACION,
            O.ID_USUARIO,
            O.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            C.NOMBRE_CATEGORIA,
            O.NOMBRE_OBLIGACION,
            O.DESCRIPCION_OBLIGACION,
            O.MONTO_FIJO_MENSUAL,
            O.DIA_VENCIMIENTO,
            O.VIGENTE,
            O.FECHA_INICIO,
            O.FECHA_FINALIZACION,
            FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION),
            O.CREADO_POR,
            O.MODIFICADO_POR,
            O.CREADO_EN,
            O.MODIFICADO_EN
        FROM OBLIGACION_FIJA O
        INNER JOIN SUBCATEGORIA S 
        ON S.ID_SUBCATEGORIA = O.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C 
        ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE O.ID_OBLIGACION = :P_ID_OBLIGACION
        INTO
            :ID_OBLIGACION,
            :ID_USUARIO,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :NOMBRE_CATEGORIA,
            :NOMBRE_OBLIGACION,
            :DESCRIPCION_OBLIGACION,
            :MONTO_FIJO_MENSUAL,
            :DIA_VENCIMIENTO,
            :VIGENTE,
            :FECHA_INICIO,
            :FECHA_FINALIZACION,
            :DIAS_PARA_VENCER,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_OBLIGACIONES_USUARIO (
    P_ID_USUARIO INTEGER,
    P_VIGENTE BOOLEAN
)
RETURNS (
    ID_OBLIGACION INTEGER,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    NOMBRE_CATEGORIA VARCHAR(60),
    NOMBRE_OBLIGACION VARCHAR(100),
    MONTO_FIJO_MENSUAL DECIMAL(18,2),
    DIA_VENCIMIENTO INTEGER,
    VIGENTE BOOLEAN,
    DIAS_PARA_VENCER INTEGER
)
AS
BEGIN
    FOR SELECT
            O.ID_OBLIGACION,
            O.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            C.NOMBRE_CATEGORIA,
            O.NOMBRE_OBLIGACION,
            O.MONTO_FIJO_MENSUAL,
            O.DIA_VENCIMIENTO,
            O.VIGENTE,
            FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION)
        FROM OBLIGACION_FIJA O
        INNER JOIN SUBCATEGORIA S 
        ON S.ID_SUBCATEGORIA = O.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C 
        ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE O.ID_USUARIO = :P_ID_USUARIO
          AND (:P_VIGENTE IS NULL OR O.VIGENTE = :P_VIGENTE)
        ORDER BY O.DIA_VENCIMIENTO, O.NOMBRE_OBLIGACION
        INTO
            :ID_OBLIGACION,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :NOMBRE_CATEGORIA,
            :NOMBRE_OBLIGACION,
            :MONTO_FIJO_MENSUAL,
            :DIA_VENCIMIENTO,
            :VIGENTE,
            :DIAS_PARA_VENCER
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_OBLIGACION (
    P_ID_OBLIGACION INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_NOMBRE_OBLIGACION VARCHAR(100),
    P_DESCRIPCION_OBLIGACION VARCHAR(200),
    P_MONTO_FIJO_MENSUAL DECIMAL(18,2),
    P_DIA_VENCIMIENTO INTEGER,
    P_FECHA_INICIO DATE,
    P_FECHA_FINALIZACION DATE,
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE OBLIGACION_FIJA
    SET ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA,
        NOMBRE_OBLIGACION = :P_NOMBRE_OBLIGACION,
        DESCRIPCION_OBLIGACION = :P_DESCRIPCION_OBLIGACION,
        MONTO_FIJO_MENSUAL = :P_MONTO_FIJO_MENSUAL,
        DIA_VENCIMIENTO = :P_DIA_VENCIMIENTO,
        FECHA_INICIO = :P_FECHA_INICIO,
        FECHA_FINALIZACION = :P_FECHA_FINALIZACION,
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_OBLIGACION = :P_ID_OBLIGACION;
END^



CREATE OR ALTER PROCEDURE SP_ELIMINAR_OBLIGACION (
    P_ID_OBLIGACION INTEGER,
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE OBLIGACION_FIJA
    SET VIGENTE = FALSE,
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_OBLIGACION = :P_ID_OBLIGACION;
END^

SET TERM ; ^