CREATE OR ALTER EXCEPTION EX_PRESUPUESTO_VIGENTE
'No se puede cerrar el presupuesto porque su periodo de vigencia todavia no termina';


SET TERM ^ ;



CREATE OR ALTER PROCEDURE SP_CREAR_PRESUPUESTO_COMPLETO (
    P_ID_USUARIO INTEGER,
    P_NOMBRE_PRESUPUESTO VARCHAR(100),
    P_ANIO_INICIO INTEGER,
    P_MES_INICIO INTEGER,
    P_ANIO_FIN INTEGER,
    P_MES_FIN INTEGER,
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    EXECUTE PROCEDURE SP_INSERTAR_PRESUPUESTO(
        :P_ID_USUARIO,
        :P_NOMBRE_PRESUPUESTO,
        :P_ANIO_INICIO,
        :P_MES_INICIO,
        :P_ANIO_FIN,
        :P_MES_FIN,
        :P_CREADO_POR
    )
    RETURNING_VALUES :NUEVO_ID;
END^



CREATE OR ALTER PROCEDURE SP_REGISTRAR_TRANSACCION_COMPLETA (
    P_ID_USUARIO INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_TIPO_TRANSACCION VARCHAR(20),
    P_DESCRIPCION VARCHAR(200),
    P_MONTO DECIMAL(18,2),
    P_FECHA DATE,
    P_METODO_PAGO VARCHAR(30),
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER,
    ADVERTENCIA VARCHAR(200)
)
AS
BEGIN
    EXECUTE PROCEDURE SP_INSERTAR_TRANSACCION(
        :P_ID_USUARIO,
        :P_ID_PRESUPUESTO,
        :P_ANIO,
        :P_MES,
        :P_ID_SUBCATEGORIA,
        NULL,
        :P_TIPO_TRANSACCION,
        :P_DESCRIPCION,
        :P_MONTO,
        :P_FECHA,
        :P_METODO_PAGO,
        NULL,
        NULL,
        :P_CREADO_POR
    )
    RETURNING_VALUES :NUEVO_ID;

    ADVERTENCIA = NULL;

    IF (P_ANIO <> EXTRACT(YEAR FROM P_FECHA) OR P_MES <> EXTRACT(MONTH FROM P_FECHA)) THEN
        ADVERTENCIA = 'El anio y mes indicados no coinciden con la fecha real del movimiento';
END^



CREATE OR ALTER PROCEDURE SP_PROCESAR_OBLIGACIONES_MES (
    P_ID_USUARIO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_ID_PRESUPUESTO INTEGER
)
RETURNS (
    ID_OBLIGACION INTEGER,
    NOMBRE_OBLIGACION VARCHAR(100),
    MONTO_FIJO_MENSUAL DECIMAL(18,2),
    DIA_VENCIMIENTO INTEGER,
    DIAS_PARA_VENCER INTEGER,
    ESTADO_PAGO VARCHAR(20),
    ALERTA VARCHAR(200)
)
AS
DECLARE VARIABLE PAGOS INTEGER;
BEGIN
    FOR SELECT
            O.ID_OBLIGACION,
            O.NOMBRE_OBLIGACION,
            O.MONTO_FIJO_MENSUAL,
            O.DIA_VENCIMIENTO,
            FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION)
        FROM OBLIGACION_FIJA O
        WHERE O.ID_USUARIO = :P_ID_USUARIO
          AND O.VIGENTE = TRUE
        ORDER BY O.DIA_VENCIMIENTO
        INTO
            :ID_OBLIGACION,
            :NOMBRE_OBLIGACION,
            :MONTO_FIJO_MENSUAL,
            :DIA_VENCIMIENTO,
            :DIAS_PARA_VENCER
    DO
    BEGIN
        SELECT COUNT(*)
        FROM TRANSACCION
        WHERE ID_OBLIGACION = :ID_OBLIGACION
          AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
          AND ANIO = :P_ANIO
          AND MES = :P_MES
        INTO :PAGOS;

        ALERTA = NULL;

        IF (PAGOS > 0) THEN
            ESTADO_PAGO = 'pagado';
        ELSE
        BEGIN
            IF (DIAS_PARA_VENCER < 0) THEN
            BEGIN
                ESTADO_PAGO = 'vencido';
                ALERTA = 'La obligacion vencio y no tiene pago registrado';
            END
            ELSE
            BEGIN
                ESTADO_PAGO = 'pendiente';

                IF (DIAS_PARA_VENCER <= 3) THEN
                    ALERTA = 'La obligacion vence en 3 dias o menos';
            END
        END

        SUSPEND;
    END
END^



CREATE OR ALTER PROCEDURE SP_CALCULAR_BALANCE_MENSUAL (
    P_ID_USUARIO INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS (
    TOTAL_INGRESOS DECIMAL(18,2),
    TOTAL_GASTOS DECIMAL(18,2),
    TOTAL_AHORROS DECIMAL(18,2),
    BALANCE_FINAL DECIMAL(18,2)
)
AS
BEGIN
    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANIO = :P_ANIO
      AND MES = :P_MES
      AND TIPO_TRANSACCION = 'ingreso'
    INTO :TOTAL_INGRESOS;

    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANIO = :P_ANIO
      AND MES = :P_MES
      AND TIPO_TRANSACCION = 'gasto'
    INTO :TOTAL_GASTOS;

    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANIO = :P_ANIO
      AND MES = :P_MES
      AND TIPO_TRANSACCION = 'ahorro'
    INTO :TOTAL_AHORROS;

    BALANCE_FINAL = TOTAL_INGRESOS - TOTAL_GASTOS - TOTAL_AHORROS;

    SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_CALCULAR_MONTO_EJECUTADO_MES (
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS (
    MONTO_EJECUTADO DECIMAL(18,2)
)
AS
BEGIN
    MONTO_EJECUTADO = FN_CALCULAR_MONTO_EJECUTADO(:P_ID_SUBCATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);
    SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_CALCULAR_PORCENTAJE_EJECUCION_MES (
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS (
    PORCENTAJE DECIMAL(18,2)
)
AS
BEGIN
    PORCENTAJE = FN_CALCULAR_PORCENTAJE_EJECUTADO(:P_ID_SUBCATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);
    SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_OBTENER_RESUMEN_CATEGORIA_MES (
    P_ID_CATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS (
    MONTO_PRESUPUESTADO DECIMAL(18,2),
    MONTO_EJECUTADO DECIMAL(18,2),
    PORCENTAJE DECIMAL(18,2)
)
AS
BEGIN
    MONTO_PRESUPUESTADO = FN_OBTENER_TOTAL_CATEGORIA_MES(:P_ID_CATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);
    MONTO_EJECUTADO = FN_OBTENER_TOTAL_EJECUTADO_CATEGORIA_MES(:P_ID_CATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);

    IF (MONTO_PRESUPUESTADO = 0) THEN
        PORCENTAJE = 0;
    ELSE
        PORCENTAJE = (MONTO_EJECUTADO / MONTO_PRESUPUESTADO) * 100;

    SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_CERRAR_PRESUPUESTO (
    P_ID_PRESUPUESTO INTEGER,
    P_MODIFICADO_POR INTEGER
)
RETURNS (
    TOTAL_PRESUPUESTADO DECIMAL(18,2),
    TOTAL_EJECUTADO DECIMAL(18,2),
    PORCENTAJE DECIMAL(18,2)
)
AS
DECLARE VARIABLE FIN INTEGER;
DECLARE VARIABLE ACTUAL INTEGER;
DECLARE VARIABLE MESES INTEGER;
BEGIN
    SELECT (ANIO_FIN * 12) + MES_FIN,
           ((ANIO_FIN * 12) + MES_FIN) - ((ANIO_INICIO * 12) + MES_INICIO) + 1
    FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :FIN, :MESES;

    ACTUAL = (EXTRACT(YEAR FROM CURRENT_DATE) * 12) + EXTRACT(MONTH FROM CURRENT_DATE);

    IF (FIN >= ACTUAL) THEN
        EXCEPTION EX_PRESUPUESTO_VIGENTE;

    SELECT COALESCE(SUM(MONTO_MENSUAL_ASIGNADO), 0) * :MESES
    FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :TOTAL_PRESUPUESTADO;

    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :TOTAL_EJECUTADO;

    IF (TOTAL_PRESUPUESTADO = 0) THEN
        PORCENTAJE = 0;
    ELSE
        PORCENTAJE = (TOTAL_EJECUTADO / TOTAL_PRESUPUESTADO) * 100;

    UPDATE PRESUPUESTO
    SET ESTADO_PRESUPUESTO = 'cerrado',
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO;

    SUSPEND;
END^

SET TERM ; ^

