SET TERM ^ ;



CREATE OR ALTER PROCEDURE SP_INSERTAR_USUARIO (
    P_NOMBRES VARCHAR(80),
    P_APELLIDOS VARCHAR(80),
    P_CORREO VARCHAR(120),
    P_SALARIO_MENSUAL_BASE DECIMAL(18,2),
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    INSERT INTO USUARIO (
        NOMBRES,
        APELLIDOS,
        CORREO,
        FECHA_REGISTRO,
        SALARIO_MENSUAL_BASE,
        ESTADO_USUARIO,
        CREADO_POR
    )
    VALUES (
        :P_NOMBRES,
        :P_APELLIDOS,
        :P_CORREO,
        CURRENT_TIMESTAMP,
        :P_SALARIO_MENSUAL_BASE,
        'activo',
        :P_CREADO_POR
    )
    RETURNING ID_USUARIO INTO :NUEVO_ID;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_USUARIO (
    P_ID_USUARIO INTEGER,
    P_NOMBRES VARCHAR(80),
    P_APELLIDOS VARCHAR(80),
    P_CORREO VARCHAR(120),
    P_SALARIO_MENSUAL_BASE DECIMAL(18,2),
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE USUARIO
    SET NOMBRES = :P_NOMBRES,
        APELLIDOS = :P_APELLIDOS,
        CORREO = :P_CORREO,
        SALARIO_MENSUAL_BASE = :P_SALARIO_MENSUAL_BASE,
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_USUARIO = :P_ID_USUARIO;
END^



CREATE OR ALTER PROCEDURE SP_ELIMINAR_USUARIO (
    P_ID_USUARIO INTEGER,
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE USUARIO
    SET ESTADO_USUARIO = 'inactivo',
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_USUARIO = :P_ID_USUARIO;
END^



CREATE OR ALTER PROCEDURE SP_CONSULTAR_USUARIO (
    P_ID_USUARIO INTEGER
)
RETURNS (
    ID_USUARIO INTEGER,
    NOMBRES VARCHAR(80),
    APELLIDOS VARCHAR(80),
    CORREO VARCHAR(120),
    FECHA_REGISTRO TIMESTAMP,
    SALARIO_MENSUAL_BASE DECIMAL(18,2),
    ESTADO_USUARIO VARCHAR(20),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            U.ID_USUARIO,
            U.NOMBRES,
            U.APELLIDOS,
            U.CORREO,
            U.FECHA_REGISTRO,
            U.SALARIO_MENSUAL_BASE,
            U.ESTADO_USUARIO,
            U.CREADO_POR,
            U.MODIFICADO_POR,
            U.CREADO_EN,
            U.MODIFICADO_EN
        FROM USUARIO U
        WHERE U.ID_USUARIO = :P_ID_USUARIO
        INTO
            :ID_USUARIO,
            :NOMBRES,
            :APELLIDOS,
            :CORREO,
            :FECHA_REGISTRO,
            :SALARIO_MENSUAL_BASE,
            :ESTADO_USUARIO,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_USUARIOS
RETURNS (
    ID_USUARIO INTEGER,
    NOMBRES VARCHAR(80),
    APELLIDOS VARCHAR(80),
    CORREO VARCHAR(120),
    SALARIO_MENSUAL_BASE DECIMAL(18,2),
    ESTADO_USUARIO VARCHAR(20),
    FECHA_REGISTRO TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            U.ID_USUARIO,
            U.NOMBRES,
            U.APELLIDOS,
            U.CORREO,
            U.SALARIO_MENSUAL_BASE,
            U.ESTADO_USUARIO,
            U.FECHA_REGISTRO
        FROM USUARIO U
        ORDER BY U.APELLIDOS, U.NOMBRES
        INTO
            :ID_USUARIO,
            :NOMBRES,
            :APELLIDOS,
            :CORREO,
            :SALARIO_MENSUAL_BASE,
            :ESTADO_USUARIO,
            :FECHA_REGISTRO
    DO
        SUSPEND;
END^

SET TERM ; ^



