CREATE OR ALTER EXCEPTION EX_SUBCATEGORIA_EN_USO
'No se puede eliminar la subcategoria porque tiene presupuestos o transacciones registradas';

CREATE OR ALTER EXCEPTION EX_SUBCATEGORIA_POR_DEFECTO
'No se puede eliminar la subcategoria General porque toda categoria debe tener al menos una';

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_INSERTAR_SUBCATEGORIA (
    P_ID_CATEGORIA INTEGER,
    P_NOMBRE_SUBCATEGORIA VARCHAR(60),
    P_DESCRIPCION_SUBCATEGORIA VARCHAR(150),
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    INSERT INTO SUBCATEGORIA (
        ID_CATEGORIA,
        NOMBRE_SUBCATEGORIA,
        DESCRIPCION_SUBCATEGORIA,
        ACTIVA,
        ES_DEFECTO,
        CREADO_POR
    )
    VALUES (
        :P_ID_CATEGORIA,
        :P_NOMBRE_SUBCATEGORIA,
        :P_DESCRIPCION_SUBCATEGORIA,
        TRUE,
        FALSE,
        :P_CREADO_POR
    )
    RETURNING ID_SUBCATEGORIA INTO :NUEVO_ID;
END^



CREATE OR ALTER PROCEDURE SP_CONSULTAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA INTEGER
)
RETURNS (
    ID_SUBCATEGORIA INTEGER,
    ID_CATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    DESCRIPCION_SUBCATEGORIA VARCHAR(150),
    ACTIVA BOOLEAN,
    ES_DEFECTO BOOLEAN,
    NOMBRE_CATEGORIA VARCHAR(60),
    TIPO_CATEGORIA VARCHAR(20),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            S.ID_SUBCATEGORIA,
            S.ID_CATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            S.DESCRIPCION_SUBCATEGORIA,
            S.ACTIVA,
            S.ES_DEFECTO,
            C.NOMBRE_CATEGORIA,
            C.TIPO_CATEGORIA,
            S.CREADO_POR,
            S.MODIFICADO_POR,
            S.CREADO_EN,
            S.MODIFICADO_EN
        FROM SUBCATEGORIA S
        INNER JOIN CATEGORIA C ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE S.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
        INTO
            :ID_SUBCATEGORIA,
            :ID_CATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :DESCRIPCION_SUBCATEGORIA,
            :ACTIVA,
            :ES_DEFECTO,
            :NOMBRE_CATEGORIA,
            :TIPO_CATEGORIA,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_SUBCATEGORIAS_POR_CATEGORIA (
    P_ID_CATEGORIA INTEGER
)
RETURNS (
    ID_SUBCATEGORIA INTEGER,
    ID_CATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    DESCRIPCION_SUBCATEGORIA VARCHAR(150),
    ACTIVA BOOLEAN,
    ES_DEFECTO BOOLEAN
)
AS
BEGIN
    FOR SELECT
            S.ID_SUBCATEGORIA,
            S.ID_CATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            S.DESCRIPCION_SUBCATEGORIA,
            S.ACTIVA,
            S.ES_DEFECTO
        FROM SUBCATEGORIA S
        WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
        ORDER BY S.ES_DEFECTO DESC, S.NOMBRE_SUBCATEGORIA
        INTO
            :ID_SUBCATEGORIA,
            :ID_CATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :DESCRIPCION_SUBCATEGORIA,
            :ACTIVA,
            :ES_DEFECTO
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA INTEGER,
    P_NOMBRE_SUBCATEGORIA VARCHAR(60),
    P_DESCRIPCION_SUBCATEGORIA VARCHAR(150),
    P_ACTIVA BOOLEAN,
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE SUBCATEGORIA
    SET NOMBRE_SUBCATEGORIA = :P_NOMBRE_SUBCATEGORIA,
        DESCRIPCION_SUBCATEGORIA = :P_DESCRIPCION_SUBCATEGORIA,
        ACTIVA = COALESCE(:P_ACTIVA, TRUE),
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA;
END^


CREATE OR ALTER PROCEDURE SP_ELIMINAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA INTEGER
)
AS
DECLARE VARIABLE CANTIDAD INTEGER;
DECLARE VARIABLE POR_DEFECTO BOOLEAN;
BEGIN
    SELECT ES_DEFECTO
    FROM SUBCATEGORIA
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :POR_DEFECTO;

    IF (POR_DEFECTO = TRUE) THEN
        EXCEPTION EX_SUBCATEGORIA_POR_DEFECTO;

    SELECT COUNT(*)
    FROM TRANSACCION
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_SUBCATEGORIA_EN_USO;

    SELECT COUNT(*)
    FROM PRESUPUESTO_DETALLE
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_SUBCATEGORIA_EN_USO;

    SELECT COUNT(*)
    FROM OBLIGACION_FIJA
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_SUBCATEGORIA_EN_USO;

    DELETE FROM SUBCATEGORIA
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA;
END^

SET TERM ; ^