CREATE OR ALTER EXCEPTION EX_CATEGORIA_EN_USO
'No se puede eliminar la categoria porque tiene subcategorias adicionales activas';

CREATE OR ALTER EXCEPTION EX_CATEGORIA_CON_MOVIMIENTOS
'No se puede eliminar la categoria porque sus subcategorias tienen presupuestos o transacciones registradas';

SET TERM ^ ;



CREATE OR ALTER PROCEDURE SP_INSERTAR_CATEGORIA (
    P_ID_USUARIO INTEGER,
    P_NOMBRE_CATEGORIA VARCHAR(60),
    P_DESCRIPCION_CATEGORIA VARCHAR(150),
    P_TIPO_CATEGORIA VARCHAR(20),
    P_ICONO VARCHAR(50),
    P_COLOR_HEX VARCHAR(7),
    P_ORDEN_UI INTEGER,
    P_CREADO_POR INTEGER
)
RETURNS (
    NUEVO_ID INTEGER
)
AS
BEGIN
    INSERT INTO CATEGORIA (
        ID_USUARIO,
        NOMBRE_CATEGORIA,
        DESCRIPCION_CATEGORIA,
        TIPO_CATEGORIA,
        ICONO,
        COLOR_HEX,
        ORDEN_UI,
        CREADO_POR
    )
    VALUES (
        :P_ID_USUARIO,
        :P_NOMBRE_CATEGORIA,
        :P_DESCRIPCION_CATEGORIA,
        :P_TIPO_CATEGORIA,
        :P_ICONO,
        :P_COLOR_HEX,
        COALESCE(:P_ORDEN_UI, 0),
        :P_CREADO_POR
    )
    RETURNING ID_CATEGORIA INTO :NUEVO_ID;
END^


CREATE OR ALTER PROCEDURE SP_CONSULTAR_CATEGORIA (
    P_ID_CATEGORIA INTEGER
)
RETURNS (
    ID_CATEGORIA INTEGER,
    ID_USUARIO INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    DESCRIPCION_CATEGORIA VARCHAR(150),
    TIPO_CATEGORIA VARCHAR(20),
    ICONO VARCHAR(50),
    COLOR_HEX VARCHAR(7),
    ORDEN_UI INTEGER,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
)
AS
BEGIN
    FOR SELECT
            C.ID_CATEGORIA,
            C.ID_USUARIO,
            C.NOMBRE_CATEGORIA,
            C.DESCRIPCION_CATEGORIA,
            C.TIPO_CATEGORIA,
            C.ICONO,
            C.COLOR_HEX,
            C.ORDEN_UI,
            C.CREADO_POR,
            C.MODIFICADO_POR,
            C.CREADO_EN,
            C.MODIFICADO_EN
        FROM CATEGORIA C
        WHERE C.ID_CATEGORIA = :P_ID_CATEGORIA
        INTO
            :ID_CATEGORIA,
            :ID_USUARIO,
            :NOMBRE_CATEGORIA,
            :DESCRIPCION_CATEGORIA,
            :TIPO_CATEGORIA,
            :ICONO,
            :COLOR_HEX,
            :ORDEN_UI,
            :CREADO_POR,
            :MODIFICADO_POR,
            :CREADO_EN,
            :MODIFICADO_EN
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_LISTAR_CATEGORIAS (
    P_ID_USUARIO INTEGER,
    P_TIPO_CATEGORIA VARCHAR(20)
)
RETURNS (
    ID_CATEGORIA INTEGER,
    ID_USUARIO INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    DESCRIPCION_CATEGORIA VARCHAR(150),
    TIPO_CATEGORIA VARCHAR(20),
    ICONO VARCHAR(50),
    COLOR_HEX VARCHAR(7),
    ORDEN_UI INTEGER
)
AS
BEGIN
    FOR SELECT
            C.ID_CATEGORIA,
            C.ID_USUARIO,
            C.NOMBRE_CATEGORIA,
            C.DESCRIPCION_CATEGORIA,
            C.TIPO_CATEGORIA,
            C.ICONO,
            C.COLOR_HEX,
            C.ORDEN_UI
        FROM CATEGORIA C
        WHERE (C.ID_USUARIO = :P_ID_USUARIO OR C.ID_USUARIO IS NULL)
          AND (:P_TIPO_CATEGORIA IS NULL OR C.TIPO_CATEGORIA = :P_TIPO_CATEGORIA)
        ORDER BY C.ORDEN_UI, C.NOMBRE_CATEGORIA
        INTO
            :ID_CATEGORIA,
            :ID_USUARIO,
            :NOMBRE_CATEGORIA,
            :DESCRIPCION_CATEGORIA,
            :TIPO_CATEGORIA,
            :ICONO,
            :COLOR_HEX,
            :ORDEN_UI
    DO
        SUSPEND;
END^



CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_CATEGORIA (
    P_ID_CATEGORIA INTEGER,
    P_NOMBRE_CATEGORIA VARCHAR(60),
    P_DESCRIPCION_CATEGORIA VARCHAR(150),
    P_ICONO VARCHAR(50),
    P_COLOR_HEX VARCHAR(7),
    P_ORDEN_UI INTEGER,
    P_MODIFICADO_POR INTEGER
)
AS
BEGIN
    UPDATE CATEGORIA
    SET NOMBRE_CATEGORIA = :P_NOMBRE_CATEGORIA,
        DESCRIPCION_CATEGORIA = :P_DESCRIPCION_CATEGORIA,
        ICONO = :P_ICONO,
        COLOR_HEX = :P_COLOR_HEX,
        ORDEN_UI = COALESCE(:P_ORDEN_UI, 0),
        MODIFICADO_POR = :P_MODIFICADO_POR
    WHERE ID_CATEGORIA = :P_ID_CATEGORIA;
END^



CREATE OR ALTER PROCEDURE SP_ELIMINAR_CATEGORIA (
    P_ID_CATEGORIA INTEGER
)
AS
DECLARE VARIABLE CANTIDAD INTEGER;
BEGIN
    SELECT COUNT(*)
    FROM SUBCATEGORIA
    WHERE ID_CATEGORIA = :P_ID_CATEGORIA
      AND ES_DEFECTO = FALSE
      AND ACTIVA = TRUE
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_CATEGORIA_EN_USO;

    SELECT COUNT(*)
    FROM TRANSACCION T
    INNER JOIN SUBCATEGORIA S 
    ON S.ID_SUBCATEGORIA = T.ID_SUBCATEGORIA
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_CATEGORIA_CON_MOVIMIENTOS;

    SELECT COUNT(*)
    FROM PRESUPUESTO_DETALLE D
    INNER JOIN SUBCATEGORIA S 
    ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
    INTO :CANTIDAD;

    IF (CANTIDAD > 0) THEN
        EXCEPTION EX_CATEGORIA_CON_MOVIMIENTOS;

    DELETE FROM SUBCATEGORIA
    WHERE ID_CATEGORIA = :P_ID_CATEGORIA;

    DELETE FROM CATEGORIA
    WHERE ID_CATEGORIA = :P_ID_CATEGORIA;
END^

SET TERM ; ^



