SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_REPORTE_GASTOS_CATEGORIA (
    P_ID_USUARIO INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS (
    ID_CATEGORIA INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    MONTO_GASTADO DECIMAL(18,2),
    CANTIDAD_TRANSACCIONES INTEGER,
    PORCENTAJE DECIMAL(18,2)
)
AS
DECLARE VARIABLE TOTAL_GASTOS DECIMAL(18,2);
BEGIN
    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANIO = :P_ANIO
      AND MES = :P_MES
      AND TIPO_TRANSACCION = 'gasto'
    INTO :TOTAL_GASTOS;

    FOR SELECT
            C.ID_CATEGORIA,
            C.NOMBRE_CATEGORIA,
            COALESCE(SUM(T.MONTO), 0),
            COUNT(T.ID_TRANSACCION)
        FROM CATEGORIA C
        INNER JOIN SUBCATEGORIA S ON S.ID_CATEGORIA = C.ID_CATEGORIA
        INNER JOIN TRANSACCION T ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        WHERE T.ID_USUARIO = :P_ID_USUARIO
          AND T.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
          AND T.ANIO = :P_ANIO
          AND T.MES = :P_MES
          AND T.TIPO_TRANSACCION = 'gasto'
        GROUP BY C.ID_CATEGORIA, C.NOMBRE_CATEGORIA
        ORDER BY 3 DESC
        INTO
            :ID_CATEGORIA,
            :NOMBRE_CATEGORIA,
            :MONTO_GASTADO,
            :CANTIDAD_TRANSACCIONES
    DO
    BEGIN
        IF (TOTAL_GASTOS = 0) THEN
            PORCENTAJE = 0;
        ELSE
            PORCENTAJE = (MONTO_GASTADO / TOTAL_GASTOS) * 100;

        SUSPEND;
    END
END^


CREATE OR ALTER PROCEDURE SP_REPORTE_CUMPLIMIENTO (
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER,
    P_TIPO_CATEGORIA VARCHAR(20)
)
RETURNS (
    ID_CATEGORIA INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    TIPO_CATEGORIA VARCHAR(20),
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    MONTO_PRESUPUESTADO DECIMAL(18,2),
    MONTO_EJECUTADO DECIMAL(18,2),
    DIFERENCIA DECIMAL(18,2),
    PORCENTAJE DECIMAL(18,2)
)
AS
BEGIN
    FOR SELECT
            C.ID_CATEGORIA,
            C.NOMBRE_CATEGORIA,
            C.TIPO_CATEGORIA,
            S.ID_SUBCATEGORIA,
            S.NOMBRE_SUBCATEGORIA,
            D.MONTO_MENSUAL_ASIGNADO
        FROM PRESUPUESTO_DETALLE D
        INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
        INNER JOIN CATEGORIA C ON C.ID_CATEGORIA = S.ID_CATEGORIA
        WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
          AND (:P_TIPO_CATEGORIA IS NULL OR C.TIPO_CATEGORIA = :P_TIPO_CATEGORIA)
        ORDER BY C.ORDEN_UI, S.NOMBRE_SUBCATEGORIA
        INTO
            :ID_CATEGORIA,
            :NOMBRE_CATEGORIA,
            :TIPO_CATEGORIA,
            :ID_SUBCATEGORIA,
            :NOMBRE_SUBCATEGORIA,
            :MONTO_PRESUPUESTADO
    DO
    BEGIN
        MONTO_EJECUTADO = FN_CALCULAR_MONTO_EJECUTADO(:ID_SUBCATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);

        DIFERENCIA = MONTO_PRESUPUESTADO - MONTO_EJECUTADO;

        IF (MONTO_PRESUPUESTADO = 0) THEN
            PORCENTAJE = 0;
        ELSE
            PORCENTAJE = (MONTO_EJECUTADO / MONTO_PRESUPUESTADO) * 100;

        SUSPEND;
    END
END^


SET TERM ; ^