SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_REPORTE_GASTOS_CATEGORIA (
    P_ID_USUARIO INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS (
    ID_CATEGORIA INTEGER,
    NOMBRE_CATEGORIA VARCHAR(60),
    MONTO_GASTADO DECIMAL(18,2),
    CANTIDAD_TRANSACCIONES INTEGER,
    PORCENTAJE DECIMAL(18,2)
)
AS
DECLARE VARIABLE TOTAL_GASTOS DECIMAL(18,2);
BEGIN
    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANIO = :P_ANIO
      AND MES = :P_MES
      AND TIPO_TRANSACCION = 'gasto'
    INTO :TOTAL_GASTOS;

    FOR SELECT
            C.ID_CATEGORIA,
            C.NOMBRE_CATEGORIA,
            COALESCE(SUM(T.MONTO), 0),
            COUNT(T.ID_TRANSACCION)
        FROM CATEGORIA C
        INNER JOIN SUBCATEGORIA S ON S.ID_CATEGORIA = C.ID_CATEGORIA
        INNER JOIN TRANSACCION T ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        WHERE T.ID_USUARIO = :P_ID_USUARIO
          AND T.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
          AND T.ANIO = :P_ANIO
          AND T.MES = :P_MES
          AND T.TIPO_TRANSACCION = 'gasto'
        GROUP BY C.ID_CATEGORIA, C.NOMBRE_CATEGORIA
        ORDER BY 3 DESC
        INTO
            :ID_CATEGORIA,
            :NOMBRE_CATEGORIA,
            :MONTO_GASTADO,
            :CANTIDAD_TRANSACCIONES
    DO
    BEGIN
        IF (TOTAL_GASTOS = 0) THEN
            PORCENTAJE = 0;
        ELSE
            PORCENTAJE = (MONTO_GASTADO / TOTAL_GASTOS) * 100;

        SUSPEND;
    END
END^

SET TERM ; ^