DELETE FROM TRANSACCION;
DELETE FROM PRESUPUESTO_DETALLE;
DELETE FROM OBLIGACION_FIJA;
DELETE FROM PRESUPUESTO;
DELETE FROM SUBCATEGORIA;
DELETE FROM CATEGORIA;
DELETE FROM USUARIO;


-- Usuario

INSERT INTO USUARIO (ID_USUARIO, NOMBRES, APELLIDOS, CORREO, FECHA_REGISTRO, SALARIO_MENSUAL_BASE, ESTADO_USUARIO)
VALUES (1, 'Brayan', 'Pinel', 'brayan.pinel@correo.com', CURRENT_TIMESTAMP, 18000, 'activo');


-- Categorias

INSERT INTO CATEGORIA (ID_CATEGORIA, ID_USUARIO, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA, ICONO, COLOR_HEX, ORDEN_UI, CREADO_POR)
VALUES (1, 1, 'Salario Principal', 'Ingreso mensual fijo', 'ingreso', 'billete', '#27AE60', 1, 1);

INSERT INTO CATEGORIA (ID_CATEGORIA, ID_USUARIO, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA, ICONO, COLOR_HEX, ORDEN_UI, CREADO_POR)
VALUES (2, 1, 'Alimentacion', 'Comida del hogar y fuera de casa', 'gasto', 'carrito', '#E67E22', 2, 1);

INSERT INTO CATEGORIA (ID_CATEGORIA, ID_USUARIO, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA, ICONO, COLOR_HEX, ORDEN_UI, CREADO_POR)
VALUES (3, 1, 'Servicios Publicos', 'Luz, agua e internet', 'gasto', 'foco', '#F1C40F', 3, 1);

INSERT INTO CATEGORIA (ID_CATEGORIA, ID_USUARIO, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA, ICONO, COLOR_HEX, ORDEN_UI, CREADO_POR)
VALUES (4, 1, 'Transporte', 'Movilizacion diaria', 'gasto', 'carro', '#3498DB', 4, 1);

INSERT INTO CATEGORIA (ID_CATEGORIA, ID_USUARIO, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA, ICONO, COLOR_HEX, ORDEN_UI, CREADO_POR)
VALUES (5, 1, 'Vivienda', 'Gastos del lugar donde vivo', 'gasto', 'casa', '#9B59B6', 5, 1);

INSERT INTO CATEGORIA (ID_CATEGORIA, ID_USUARIO, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA, ICONO, COLOR_HEX, ORDEN_UI, CREADO_POR)
VALUES (6, 1, 'Ahorro', 'Dinero que aparto cada mes', 'ahorro', 'alcancia', '#16A085', 6, 1);


-- Subcategorias

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (101, 1, 'Salario Base', 'Sueldo quincenal acumulado', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (102, 2, 'Supermercado', 'Compras de despensa', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (103, 2, 'Restaurantes', 'Comida fuera de casa', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (104, 3, 'Energia Electrica', 'Recibo de luz', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (105, 3, 'Agua', 'Recibo de agua potable', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (106, 3, 'Internet', 'Servicio de internet del hogar', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (107, 4, 'Combustible', 'Gasolina del vehiculo', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (108, 4, 'Transporte Publico', 'Buses y taxis', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (109, 5, 'Alquiler', 'Renta mensual de la casa', TRUE, FALSE, 1);

INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, ID_CATEGORIA, NOMBRE_SUBCATEGORIA, DESCRIPCION_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_POR)
VALUES (110, 6, 'Fondo de Emergencia', 'Reserva para imprevistos', TRUE, FALSE, 1);


-- Presupuesto de dos meses

INSERT INTO PRESUPUESTO (ID_PRESUPUESTO, ID_USUARIO, NOMBRE_PRESUPUESTO, ANIO_INICIO, MES_INICIO, ANIO_FIN, MES_FIN,
    TOTAL_INGRESOS_PLANIFICADOS, TOTAL_GASTOS_PLANIFICADOS, TOTAL_AHORRO_PLANIFICADO,
    FECHA_CREACION, ESTADO_PRESUPUESTO, CREADO_POR)
VALUES (1, 1, 'Presupuesto Enero-Febrero 2026', 2026, 1, 2026, 2, 0, 0, 0, CURRENT_TIMESTAMP, 'activo', 1);


-- Detalles del presupuesto

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 101, 18000, 'Sueldo mensual', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 102, 4000, 'Despensa de cada semana', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 103, 1500, 'Salidas a comer', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 104, 900, 'Promedio del recibo de luz', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 105, 350, 'Recibo de agua', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 106, 800, 'Plan de internet', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 107, 2000, 'Gasolina del mes', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 108, 400, 'Buses ocasionales', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 109, 5000, 'Renta de la casa', 1);

INSERT INTO PRESUPUESTO_DETALLE (ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO_MENSUAL_ASIGNADO, OBSERVACIONES, CREADO_POR)
VALUES (1, 110, 2000, 'Meta de ahorro mensual', 1);


-- Obligaciones fijas

INSERT INTO OBLIGACION_FIJA (ID_OBLIGACION, ID_USUARIO, ID_SUBCATEGORIA, NOMBRE_OBLIGACION, DESCRIPCION_OBLIGACION,
    MONTO_FIJO_MENSUAL, DIA_VENCIMIENTO, VIGENTE, FECHA_INICIO, FECHA_FINALIZACION, CREADO_POR)
VALUES (1, 1, 109, 'Alquiler de vivienda', 'Renta mensual del apartamento', 5000, 5, TRUE, '2025-06-01', NULL, 1);

INSERT INTO OBLIGACION_FIJA (ID_OBLIGACION, ID_USUARIO, ID_SUBCATEGORIA, NOMBRE_OBLIGACION, DESCRIPCION_OBLIGACION,
    MONTO_FIJO_MENSUAL, DIA_VENCIMIENTO, VIGENTE, FECHA_INICIO, FECHA_FINALIZACION, CREADO_POR)
VALUES (2, 1, 106, 'Internet residencial', 'Plan de fibra optica', 800, 10, TRUE, '2025-06-01', NULL, 1);

INSERT INTO OBLIGACION_FIJA (ID_OBLIGACION, ID_USUARIO, ID_SUBCATEGORIA, NOMBRE_OBLIGACION, DESCRIPCION_OBLIGACION,
    MONTO_FIJO_MENSUAL, DIA_VENCIMIENTO, VIGENTE, FECHA_INICIO, FECHA_FINALIZACION, CREADO_POR)
VALUES (3, 1, 104, 'Energia electrica', 'Recibo mensual de luz', 900, 15, TRUE, '2025-06-01', NULL, 1);

INSERT INTO OBLIGACION_FIJA (ID_OBLIGACION, ID_USUARIO, ID_SUBCATEGORIA, NOMBRE_OBLIGACION, DESCRIPCION_OBLIGACION,
    MONTO_FIJO_MENSUAL, DIA_VENCIMIENTO, VIGENTE, FECHA_INICIO, FECHA_FINALIZACION, CREADO_POR)
VALUES (4, 1, 105, 'Agua potable', 'Recibo mensual de agua', 350, 18, TRUE, '2025-06-01', NULL, 1);


-- ENERO 2026

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 101, NULL, 'ingreso', 'Salario del mes', 18000, '2026-01-01', 'transferencia', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 102, NULL, 'gasto', 'Compra semanal', 980, '2026-01-04', 'tarjeta_debito', 'F-1041', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 109, 1, 'gasto', 'Pago de alquiler', 5000, '2026-01-05', 'transferencia', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 107, NULL, 'gasto', 'Tanque de gasolina', 700, '2026-01-07', 'tarjeta_credito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 103, NULL, 'gasto', 'Almuerzo con amigos', 320, '2026-01-09', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 106, 2, 'gasto', 'Pago de internet', 800, '2026-01-10', 'tarjeta_debito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 102, NULL, 'gasto', 'Compra semanal', 1120, '2026-01-11', 'tarjeta_debito', 'F-1108', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 108, NULL, 'gasto', 'Pasajes de bus', 120, '2026-01-13', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 104, 3, 'gasto', 'Pago de energia electrica', 920, '2026-01-15', 'tarjeta_debito', NULL, 'Subio un poco este mes', CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 103, NULL, 'gasto', 'Cena familiar', 450, '2026-01-17', 'tarjeta_credito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 105, 4, 'gasto', 'Pago de agua', 340, '2026-01-18', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 102, NULL, 'gasto', 'Compra semanal', 860, '2026-01-19', 'tarjeta_debito', 'F-1187', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 107, NULL, 'gasto', 'Tanque de gasolina', 750, '2026-01-21', 'tarjeta_credito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 103, NULL, 'gasto', 'Comida rapida', 280, '2026-01-24', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 102, NULL, 'gasto', 'Compra semanal', 1150, '2026-01-26', 'tarjeta_debito', 'F-1244', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 108, NULL, 'gasto', 'Taxi por lluvia', 150, '2026-01-28', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 1, 110, NULL, 'ahorro', 'Aporte al fondo de emergencia', 2000, '2026-01-30', 'transferencia', NULL, NULL, CURRENT_TIMESTAMP, 1);


-- FEBRERO 2026

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 101, NULL, 'ingreso', 'Salario del mes', 18000, '2026-02-01', 'transferencia', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 102, NULL, 'gasto', 'Compra semanal', 1050, '2026-02-03', 'tarjeta_debito', 'F-1302', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 109, 1, 'gasto', 'Pago de alquiler', 5000, '2026-02-05', 'transferencia', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 107, NULL, 'gasto', 'Tanque de gasolina', 800, '2026-02-06', 'tarjeta_credito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 103, NULL, 'gasto', 'Cena del fin de semana', 520, '2026-02-07', 'tarjeta_credito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 106, 2, 'gasto', 'Pago de internet', 800, '2026-02-10', 'tarjeta_debito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 102, NULL, 'gasto', 'Compra semanal', 890, '2026-02-10', 'tarjeta_debito', 'F-1358', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 108, NULL, 'gasto', 'Pasajes de bus', 130, '2026-02-11', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 103, NULL, 'gasto', 'Cena de san valentin', 780, '2026-02-14', 'tarjeta_credito', NULL, 'Gasto mas alto de lo normal', CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 104, 3, 'gasto', 'Pago de energia electrica', 1050, '2026-02-16', 'tarjeta_debito', NULL, 'Mes con mas consumo', CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 105, 4, 'gasto', 'Pago de agua', 365, '2026-02-17', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 102, NULL, 'gasto', 'Compra semanal', 1240, '2026-02-18', 'tarjeta_debito', 'F-1415', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 107, NULL, 'gasto', 'Tanque de gasolina', 820, '2026-02-20', 'tarjeta_credito', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 103, NULL, 'gasto', 'Almuerzo de trabajo', 340, '2026-02-21', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 108, NULL, 'gasto', 'Taxi al aeropuerto', 140, '2026-02-24', 'efectivo', NULL, NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 102, NULL, 'gasto', 'Compra semanal', 760, '2026-02-25', 'tarjeta_debito', 'F-1470', NULL, CURRENT_TIMESTAMP, 1);

INSERT INTO TRANSACCION (ID_USUARIO, ID_PRESUPUESTO, ANIO, MES, ID_SUBCATEGORIA, ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA, METODO_PAGO, NUM_FACTURA, OBSERVACIONES, FECHA_REGISTRO, CREADO_POR)
VALUES (1, 1, 2026, 2, 110, NULL, 'ahorro', 'Aporte al fondo de emergencia', 1500, '2026-02-27', 'transferencia', NULL, 'Menos que enero por gastos extra', CURRENT_TIMESTAMP, 1);


EXECUTE PROCEDURE SP_RECALCULAR_TOTALES_PRESUPUESTO(1);


ALTER TABLE USUARIO ALTER COLUMN ID_USUARIO RESTART WITH 2;
ALTER TABLE CATEGORIA ALTER COLUMN ID_CATEGORIA RESTART WITH 7;
ALTER TABLE SUBCATEGORIA ALTER COLUMN ID_SUBCATEGORIA RESTART WITH 111;
ALTER TABLE PRESUPUESTO ALTER COLUMN ID_PRESUPUESTO RESTART WITH 2;
ALTER TABLE OBLIGACION_FIJA ALTER COLUMN ID_OBLIGACION RESTART WITH 5;
