ALTER TABLE CATEGORIA 
ADD FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE SUBCATEGORIA 
ADD FOREIGN KEY (ID_CATEGORIA) 
REFERENCES CATEGORIA (ID_CATEGORIA);

ALTER TABLE PRESUPUESTO 
ADD FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE PRESUPUESTO_DETALLE 
ADD FOREIGN KEY (ID_PRESUPUESTO) 
REFERENCES PRESUPUESTO (ID_PRESUPUESTO);

ALTER TABLE PRESUPUESTO_DETALLE 
ADD FOREIGN KEY (ID_SUBCATEGORIA) 
REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

ALTER TABLE OBLIGACION_FIJA 
ADD FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE OBLIGACION_FIJA 
ADD FOREIGN KEY (ID_SUBCATEGORIA) 
REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

ALTER TABLE TRANSACCION 
ADD FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE TRANSACCION 
ADD FOREIGN KEY (ID_PRESUPUESTO) 
REFERENCES PRESUPUESTO (ID_PRESUPUESTO);

ALTER TABLE TRANSACCION 
ADD FOREIGN KEY (ID_SUBCATEGORIA) 
REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);


ALTER TABLE TRANSACCION 
ADD FOREIGN KEY (ID_OBLIGACION) 
REFERENCES OBLIGACION_FIJA (ID_OBLIGACION);