ALTER TABLE USUARIO ADD CHECK (SALARIO_MENSUAL_BASE >= 0);
ALTER TABLE USUARIO ADD CHECK (ESTADO_USUARIO IN ('activo','inactivo'));

ALTER TABLE CATEGORIA ADD CHECK (TIPO_CATEGORIA IN ('ingreso','gasto','ahorro'));

ALTER TABLE PRESUPUESTO ADD CHECK (MES_INICIO BETWEEN 1 AND 12);
ALTER TABLE PRESUPUESTO ADD CHECK (MES_FIN BETWEEN 1 AND 12);
ALTER TABLE PRESUPUESTO ADD CHECK (ESTADO_PRESUPUESTO IN ('borrador','activo','cerrado'));
ALTER TABLE PRESUPUESTO ADD CHECK (ANIO_FIN > ANIO_INICIO OR (ANIO_FIN = ANIO_INICIO AND MES_FIN >= MES_INICIO));

ALTER TABLE PRESUPUESTO_DETALLE ADD CHECK (MONTO_MENSUAL_ASIGNADO >= 0);

ALTER TABLE OBLIGACION_FIJA ADD CHECK (MONTO_FIJO_MENSUAL > 0);
ALTER TABLE OBLIGACION_FIJA ADD CHECK (DIA_VENCIMIENTO BETWEEN 1 AND 31);
ALTER TABLE OBLIGACION_FIJA ADD CHECK (FECHA_FINALIZACION IS NULL OR FECHA_FINALIZACION > FECHA_INICIO);

ALTER TABLE TRANSACCION ADD CHECK (MES BETWEEN 1 AND 12);
ALTER TABLE TRANSACCION ADD CHECK (MONTO > 0);
ALTER TABLE TRANSACCION ADD CHECK (TIPO_TRANSACCION IN ('ingreso','gasto','ahorro'));
ALTER TABLE TRANSACCION ADD CHECK (METODO_PAGO IN ('efectivo','tarjeta_debito','tarjeta_credito','transferencia'));