SET TERM ^ ;



CREATE OR ALTER FUNCTION FN_CALCULAR_MONTO_EJECUTADO (
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE TOTAL DECIMAL(18,2);
BEGIN
    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANIO = :P_ANIO
      AND MES = :P_MES
    INTO :TOTAL;

    RETURN TOTAL;
END^ 



CREATE OR ALTER FUNCTION FN_CALCULAR_PORCENTAJE_EJECUTADO (
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE PRESUPUESTADO DECIMAL(18,2);
DECLARE VARIABLE EJECUTADO DECIMAL(18,2);
BEGIN
    SELECT MONTO_MENSUAL_ASIGNADO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :PRESUPUESTADO;

    IF (PRESUPUESTADO IS NULL OR PRESUPUESTADO = 0) THEN
        RETURN 0;

    EJECUTADO = FN_CALCULAR_MONTO_EJECUTADO(:P_ID_SUBCATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);

    RETURN (EJECUTADO / PRESUPUESTADO) * 100;
END^



CREATE OR ALTER FUNCTION FN_OBTENER_BALANCE_SUBCATEGORIA (
    P_ID_PRESUPUESTO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE PRESUPUESTADO DECIMAL(18,2);
DECLARE VARIABLE EJECUTADO DECIMAL(18,2);
BEGIN
    SELECT MONTO_MENSUAL_ASIGNADO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :PRESUPUESTADO;

    IF (PRESUPUESTADO IS NULL) THEN
        PRESUPUESTADO = 0;

    EJECUTADO = FN_CALCULAR_MONTO_EJECUTADO(:P_ID_SUBCATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);

    RETURN PRESUPUESTADO - EJECUTADO;
END^



CREATE OR ALTER FUNCTION FN_OBTENER_TOTAL_CATEGORIA_MES (
    P_ID_CATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE TOTAL DECIMAL(18,2);
BEGIN
    SELECT COALESCE(SUM(D.MONTO_MENSUAL_ASIGNADO), 0)
    FROM PRESUPUESTO_DETALLE D
    INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
      AND D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :TOTAL;

    RETURN TOTAL;
END^



CREATE OR ALTER FUNCTION FN_OBTENER_TOTAL_EJECUTADO_CATEGORIA_MES (
    P_ID_CATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE TOTAL DECIMAL(18,2);
BEGIN
    SELECT COALESCE(SUM(T.MONTO), 0)
    FROM TRANSACCION T
    INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = T.ID_SUBCATEGORIA
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
      AND T.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND T.ANIO = :P_ANIO
      AND T.MES = :P_MES
    INTO :TOTAL;

    RETURN TOTAL;
END^



CREATE OR ALTER FUNCTION FN_DIAS_HASTA_VENCIMIENTO (P_ID_OBLIGACION INTEGER)
RETURNS INTEGER
AS
DECLARE VARIABLE DIA INTEGER;
DECLARE VARIABLE PRIMER_DIA DATE;
DECLARE VARIABLE ULTIMO_DIA DATE;
DECLARE VARIABLE DIA_REAL INTEGER;
DECLARE VARIABLE FECHA_VENCE DATE;
BEGIN
    SELECT DIA_VENCIMIENTO
    FROM OBLIGACION_FIJA
    WHERE ID_OBLIGACION = :P_ID_OBLIGACION
    INTO :DIA;

    IF (DIA IS NULL) THEN
        RETURN NULL;

    PRIMER_DIA = DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE);
    ULTIMO_DIA = DATEADD(DAY, -1, DATEADD(MONTH, 1, PRIMER_DIA));

    DIA_REAL = DIA;
    IF (DIA_REAL > EXTRACT(DAY FROM ULTIMO_DIA)) THEN
        DIA_REAL = EXTRACT(DAY FROM ULTIMO_DIA);

    FECHA_VENCE = DATEADD(DAY, DIA_REAL - 1, PRIMER_DIA);

    RETURN DATEDIFF(DAY, CURRENT_DATE, FECHA_VENCE);
END^



CREATE OR ALTER FUNCTION FN_VALIDAR_VIGENCIA_PRESUPUESTO (
    P_FECHA DATE,
    P_ID_PRESUPUESTO INTEGER
)
RETURNS BOOLEAN
AS
DECLARE VARIABLE INICIO INTEGER;
DECLARE VARIABLE FIN INTEGER;
DECLARE VARIABLE PERIODO INTEGER;
BEGIN
    SELECT (ANIO_INICIO * 12) + MES_INICIO, (ANIO_FIN * 12) + MES_FIN
    FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :INICIO, :FIN;

    IF (INICIO IS NULL) THEN
        RETURN FALSE;

    PERIODO = (EXTRACT(YEAR FROM :P_FECHA) * 12) + EXTRACT(MONTH FROM :P_FECHA);

    IF (PERIODO >= INICIO AND PERIODO <= FIN) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
END^



CREATE OR ALTER FUNCTION FN_OBTENER_CATEGORIA_POR_SUBCATEGORIA (P_ID_SUBCATEGORIA INTEGER)
RETURNS INTEGER
AS
DECLARE VARIABLE ID_CAT INTEGER;
BEGIN
    SELECT ID_CATEGORIA
    FROM SUBCATEGORIA
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :ID_CAT;

    RETURN ID_CAT;
END^



CREATE OR ALTER FUNCTION FN_CALCULAR_PROYECCION_GASTO_MENSUAL (
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE EJECUTADO DECIMAL(18,2);
DECLARE VARIABLE PRIMER_DIA DATE;
DECLARE VARIABLE DIAS_MES INTEGER;
DECLARE VARIABLE DIAS_PASADOS INTEGER;
BEGIN
    EJECUTADO = FN_CALCULAR_MONTO_EJECUTADO(:P_ID_SUBCATEGORIA, :P_ID_PRESUPUESTO, :P_ANIO, :P_MES);

    PRIMER_DIA = DATEADD(MONTH, ((:P_ANIO - 2000) * 12) + :P_MES - 1, CAST('2000-01-01' AS DATE));
    DIAS_MES = EXTRACT(DAY FROM DATEADD(DAY, -1, DATEADD(MONTH, 1, PRIMER_DIA)));

    IF (:P_ANIO = EXTRACT(YEAR FROM CURRENT_DATE) AND :P_MES = EXTRACT(MONTH FROM CURRENT_DATE)) THEN
        DIAS_PASADOS = EXTRACT(DAY FROM CURRENT_DATE);
    ELSE
        DIAS_PASADOS = DIAS_MES;

    IF (DIAS_PASADOS = 0) THEN
        RETURN 0;

    RETURN (EJECUTADO / DIAS_PASADOS) * DIAS_MES;
END^



CREATE OR ALTER FUNCTION FN_OBTENER_PROMEDIO_GASTO_SUBCATEGORIA (
    P_ID_USUARIO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_CANTIDAD_MESES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE TOTAL DECIMAL(18,2);
DECLARE VARIABLE PERIODO_ACTUAL INTEGER;
DECLARE VARIABLE PERIODO_DESDE INTEGER;
BEGIN
    IF (P_CANTIDAD_MESES IS NULL OR P_CANTIDAD_MESES <= 0) THEN
        RETURN 0;

    PERIODO_ACTUAL = (EXTRACT(YEAR FROM CURRENT_DATE) * 12) + EXTRACT(MONTH FROM CURRENT_DATE);
    PERIODO_DESDE = PERIODO_ACTUAL - P_CANTIDAD_MESES;

    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
      AND ((ANIO * 12) + MES) > :PERIODO_DESDE
      AND ((ANIO * 12) + MES) <= :PERIODO_ACTUAL
    INTO :TOTAL;

    RETURN TOTAL / P_CANTIDAD_MESES;
END^

SET TERM ; ^