

CREATE EXCEPTION EX_TIPO_TRANSACCION
'El tipo de la transaccion no coincide con el tipo de su categoria';

CREATE EXCEPTION EX_FUERA_VIGENCIA
'El anio y mes de la transaccion estan fuera de la vigencia del presupuesto';


SET TERM ^ ;



CREATE TRIGGER TRG_SUBCATEGORIA_DEFECTO FOR CATEGORIA
AFTER INSERT
AS
BEGIN
    INSERT INTO SUBCATEGORIA (ID_CATEGORIA, NOMBRE_SUBCATEGORIA, ACTIVA, ES_DEFECTO, CREADO_EN)
    VALUES (NEW.ID_CATEGORIA, 'General', TRUE, TRUE, CURRENT_TIMESTAMP);
END^



CREATE TRIGGER TRG_USUARIO_AUDITORIA FOR USUARIO
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^



CREATE TRIGGER TRG_CATEGORIA_AUDITORIA FOR CATEGORIA
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^



CREATE TRIGGER TRG_SUBCATEGORIA_AUDITORIA FOR SUBCATEGORIA
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^



CREATE TRIGGER TRG_PRESUPUESTO_AUDITORIA FOR PRESUPUESTO
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^



CREATE TRIGGER TRG_DETALLE_AUDITORIA FOR PRESUPUESTO_DETALLE
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^


CREATE TRIGGER TRG_OBLIGACION_AUDITORIA FOR OBLIGACION_FIJA
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^



CREATE TRIGGER TRG_TRANSACCION_AUDITORIA FOR TRANSACCION
BEFORE INSERT OR UPDATE
AS
BEGIN
    IF (INSERTING) THEN NEW.CREADO_EN = CURRENT_TIMESTAMP;
    IF (UPDATING) THEN NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^



CREATE TRIGGER TRG_TRANSACCION_VALIDA_TIPO FOR TRANSACCION
BEFORE INSERT OR UPDATE
AS
DECLARE VARIABLE TIPO_CAT VARCHAR(20);
BEGIN
    SELECT C.TIPO_CATEGORIA
    FROM SUBCATEGORIA S
    INNER JOIN CATEGORIA C ON C.ID_CATEGORIA = S.ID_CATEGORIA
    WHERE S.ID_SUBCATEGORIA = NEW.ID_SUBCATEGORIA
    INTO :TIPO_CAT;

    IF (NEW.TIPO_TRANSACCION <> TIPO_CAT) THEN
        EXCEPTION EX_TIPO_TRANSACCION;
END^



CREATE TRIGGER TRG_TRANSACCION_VALIDA_PERIODO FOR TRANSACCION
BEFORE INSERT OR UPDATE
AS
DECLARE VARIABLE INICIO INTEGER;
DECLARE VARIABLE FIN INTEGER;
BEGIN
    SELECT (ANIO_INICIO * 12) + MES_INICIO, (ANIO_FIN * 12) + MES_FIN
    FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = NEW.ID_PRESUPUESTO
    INTO :INICIO, :FIN;

    IF ((NEW.ANIO * 12) + NEW.MES < INICIO) THEN
        EXCEPTION EX_FUERA_VIGENCIA;

    IF ((NEW.ANIO * 12) + NEW.MES > FIN) THEN
        EXCEPTION EX_FUERA_VIGENCIA;
END^

SET TERM ; ^





